packages:
  - 'scripts/config'
  - 'packages/**'
  - 'e2e/**'
  - 'website'
  - '!**/compiled/**'
  - '!**/tests/**'
  - '!packages/create-rspress/template-basic'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - 'core-js'
  - 'esbuild'
  - 'nx'
