packages:
  - 'scripts/config'
  - 'packages/**'
  - 'e2e/**'
  - 'website'
  - '!**/compiled/**'
  - '!**/tests/**'
  - '!packages/create-rspress/template-basic'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - 'core-js'
  - 'esbuild'
  - 'nx'

hoistPattern: []
linkWorkspacePackages: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - tailwindcss@3.4.18
  - undici-types@6.20.0
  - semver@6.3.1
