configDependencies:
  pnpm-plugin-skills: 0.5.0+sha512-wgwqHeVDNe7KQ7sHuM1uL+/tmR7FmDJJBZNR6sHu3KTCO9K8OGdYGoPQzJSA8d2KxigjccFc7uPMSPfZ5WXbCg==

packages:
  - scripts/config
  - packages/**
  - e2e/**
  - website
  - '!**/compiled/**'
  - '!**/tests/**'
  - '!packages/create-rspress/template-*'

hoistPattern: []

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - esbuild
  - nx
  - sharp

strictPeerDependencies: false
