packages:
  - scripts/config
  - packages/**
  - e2e/**
  - website
  - '!**/compiled/**'
  - '!**/tests/**'
  - '!packages/create-rspress/template-basic'

hoistPattern: []

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - esbuild
  - nx
  - sharp

strictPeerDependencies: false
