packages:
  - scripts/config
  - packages/**
  - e2e/**
  - website
  - '!**/compiled/**'
  - '!**/tests/**'
  - '!packages/create-rspress/template-basic'

hoistPattern: []

linkWorkspacePackages: true

configDependencies:
  pnpm-plugin-skills: 0.1.0+sha512-2SVyrp5xhiejj02/5yjnxC3eSlDQOEzDT1g1EhPTJlgU+wc9Rk+uei8qrXlWwGaQ6vwscdo7plZt5g7ql8Kafw==

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - esbuild
  - nx
  - sharp

strictPeerDependencies: false
