// Icons re-exports
type Icon = React.FC<React.SVGProps<SVGSVGElement>> | string;

import { default as IconArrowDownHelper } from './assets/arrow-down.svg';
import { default as IconArrowRightHelper } from './assets/arrow-right.svg';
import { default as IconCloseHelper } from './assets/close.svg';
import { default as IconCopyHelper } from './assets/copy.svg';
import { default as IconDeprecatedHelper } from './assets/deprecated.svg';
import { default as IconDownHelper } from './assets/down.svg';
import { default as IconEmptyHelper } from './assets/empty.svg';
import { default as IconExperimentalHelper } from './assets/experimental.svg';
import { default as IconExternalLinkHelper } from './assets/external-link.svg';
import { default as IconFileHelper } from './assets/file.svg';
import { default as IconGithubHelper } from './assets/github.svg';
import { default as IconGitlabHelper } from './assets/gitlab.svg';
import { default as IconHeaderHelper } from './assets/header.svg';
import { default as IconJumpHelper } from './assets/jump.svg';
import { default as IconLinkHelper } from './assets/link.svg';
import { default as IconLoadingHelper } from './assets/loading.svg';
import { default as IconMenuHelper } from './assets/menu.svg';
import { default as IconMoonHelper } from './assets/moon.svg';
import { default as IconSearchHelper } from './assets/search.svg';
import { default as IconSmallMenuHelper } from './assets/small-menu.svg';
import { default as IconSuccessHelper } from './assets/success.svg';
import { default as IconSunHelper } from './assets/sun.svg';
import { default as IconTitleHelper } from './assets/title.svg';
import { default as IconWrapHelper } from './assets/wrap.svg';
import { default as IconWrappedHelper } from './assets/wrapped.svg';

export const IconDeprecated = IconDeprecatedHelper as Icon;
export const IconExperimental = IconExperimentalHelper as Icon;
export const IconArrowDown = IconArrowDownHelper as Icon;
export const IconArrowRight = IconArrowRightHelper as Icon;
export const IconClose = IconCloseHelper as Icon;
export const IconCopy = IconCopyHelper as Icon;
export const IconDown = IconDownHelper as Icon;
export const IconEmpty = IconEmptyHelper as Icon;
export const IconFile = IconFileHelper as Icon;
export const IconGithub = IconGithubHelper as Icon;
export const IconGitlab = IconGitlabHelper as Icon;
export const IconHeader = IconHeaderHelper as Icon;
export const IconJump = IconJumpHelper as Icon;
export const IconLoading = IconLoadingHelper as Icon;
export const IconMenu = IconMenuHelper as Icon;
export const IconMoon = IconMoonHelper as Icon;
export const IconSearch = IconSearchHelper as Icon;
export const IconSmallMenu = IconSmallMenuHelper as Icon;
export const IconSuccess = IconSuccessHelper as Icon;
export const IconSun = IconSunHelper as Icon;
export const IconTitle = IconTitleHelper as Icon;
export const IconWrap = IconWrapHelper as Icon;
export const IconWrapped = IconWrappedHelper as Icon;
export const IconExternalLink = IconExternalLinkHelper as Icon;
export const IconLink = IconLinkHelper as Icon;
