import path from 'node:path';
import { defineConfig } from '@rspress/core';
import { pluginLlms } from '@rspress/plugin-llms';

export default defineConfig({
  root: path.join(__dirname, 'doc'),
  ssg: false,
  plugins: [pluginLlms()],
  title: 'Plugin LLMS',
  description: 'llms.txt can be generated by @rspress/plugin-llms',
  themeConfig: {
    llmsUI: { placement: 'outline' },
  },
});
