import path from 'node:path';
import { pluginLlms } from '@rspress/plugin-llms';
import { defineConfig } from 'rspress/config';

export default defineConfig({
  root: path.join(__dirname, 'doc'),
  ssg: false,
  plugins: [pluginLlms()],
  title: 'Plugin LLMS',
  description: 'llms.txt can be generated by @rspress/plugin-llms',
});
