import {
  lstat,
  mkdir,
  readFile,
  readdir,
  unlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_HEADER =
  '---\n# Generated by @rspress/plugin-openapi. Do not edit.\n';
const MANIFEST = '.openapi-manifest.json';

async function readOptional(file: string): Promise<string | undefined> {
  try {
    // Do not follow symlinks when inspecting files we may replace or remove.
    if (!(await lstat(file)).isFile())
      throw new Error(`Expected a regular file: ${file}`);
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
    throw error;
  }
}

/** Write ordinary MDX pages before Rspress scans the documentation root. */
export async function generatePages(
  root: string,
  outDir: string,
  pages: { name: string; content: string }[],
  meta?: unknown[],
): Promise<void> {
  if (
    path.isAbsolute(outDir) ||
    outDir.split(/[\\/]/).some(part => !part || part === '.' || part === '..')
  ) {
    throw new Error(
      'OpenAPI outDir must be a directory inside the documentation root.',
    );
  }
  const directory = path.resolve(root, outDir);
  // Keep generated output inside the root even when a directory is a symlink.
  let current = path.resolve(root);
  for (const part of outDir.split(/[\\/]/)) {
    current = path.join(current, part);
    try {
      if ((await lstat(current)).isSymbolicLink())
        throw new Error(
          `OpenAPI output directory cannot be a symlink: ${current}`,
        );
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  }
  const entries = await readdir(directory).catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === 'ENOENT') return [];
      throw error;
    },
  );
  const existing = new Map<string, string | undefined>();
  for (const name of new Set([
    ...entries.filter(name => name.endsWith('.mdx')),
    ...pages.map(page => page.name),
  ])) {
    existing.set(name, await readOptional(path.join(directory, name)));
  }
  for (const page of pages) {
    const content = existing.get(page.name);
    if (content !== undefined && !content.startsWith(GENERATED_HEADER))
      throw new Error(
        `Refusing to overwrite an existing OpenAPI page: ${path.join(directory, page.name)}`,
      );
  }
  const metaPath = path.join(directory, '_meta.json');
  const oldMeta = await readOptional(metaPath);
  const manifestText = await readOptional(path.join(directory, MANIFEST));
  const manifest = manifestText
    ? (JSON.parse(manifestText) as { meta?: string })
    : {};
  const nextMeta =
    meta === undefined ? undefined : `${JSON.stringify(meta, null, 2)}\n`;
  const canUpdateMeta = oldMeta === undefined || oldMeta === manifest.meta;
  await mkdir(directory, { recursive: true });
  for (const page of pages) {
    if (existing.get(page.name) !== page.content)
      await writeFile(path.join(directory, page.name), page.content);
  }
  const names = new Set(pages.map(page => page.name));
  for (const [name, content] of existing) {
    if (!names.has(name) && content?.startsWith(GENERATED_HEADER))
      await unlink(path.join(directory, name));
  }
  // Preserve user-customized navigation; only refresh metadata we still own.
  if (canUpdateMeta) {
    if (nextMeta !== undefined && oldMeta !== nextMeta)
      await writeFile(metaPath, nextMeta);
    else if (nextMeta === undefined && oldMeta !== undefined)
      await unlink(metaPath);
  }
  const nextManifest = `${JSON.stringify({ meta: canUpdateMeta ? nextMeta : manifest.meta }, null, 2)}\n`;
  if (manifestText !== nextManifest)
    await writeFile(path.join(directory, MANIFEST), nextManifest);
}
