name: Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions: {}

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Install Dependencies and Build
        run: |
          pnpm install

      - name: Build Demo Project
        run: |
          cd website
          pnpm install
          RSDOCTOR=1 pnpm run build

      - name: Build auto-nav-sidebar Project
        run: RSDOCTOR=1 pnpm --filter @rspress-fixture/auto-nav-sidebar run build

      - name: Report Compressed Size
        uses: web-infra-dev/rsdoctor-action@2fbd50933702502f12d2bbef5273afbfd829a289 # main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_path: '{website,e2e/fixtures/auto-nav-sidebar}/doc_build/diff-rsdoctor/**/rsdoctor-data.json'
          target_branch: 'main'
