# https://github.com/stackblitz-labs/pkg.pr.new
name: Preview Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

permissions: {}

jobs:
  preview:
    if: github.repository == 'web-infra-dev/rspress'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          predicate-quantifier: 'every'
          filters: |
            changed:
              - "packages/**"

      - name: Setup Node.js
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: false

      - name: Install Dependencies
        if: steps.changes.outputs.changed == 'true'
        run: pnpm install

      - name: Publish Preview
        if: steps.changes.outputs.changed == 'true'
        run: pnpx pkg-pr-new publish --compact --pnpm ./packages/*
