# https://github.com/stackblitz-labs/pkg.pr.new
name: Preview Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  preview:
    if: github.repository == 'web-infra-dev/rspress'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: changes
        with:
          predicate-quantifier: 'every'
          filters: |
            changed:
              - "packages/**"

      - name: Setup Node.js
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        if: steps.changes.outputs.changed == 'true'
        run: pnpm install

      - name: Publish Preview
        if: steps.changes.outputs.changed == 'true'
        run: pnpx pkg-pr-new publish --compact --pnpm ./packages/*
